
POST http://localhost:8080/api/patients
Content-Type: application/json

{
  "firstName": "Адильжан",
  "lastName": "Абдамбаев",
  "age": 20,
  "illness": "Болит нога"
}

GET http://localhost:8080/api/patients


