
POST http://localhost:8080/api/patients
Content-Type: application/json

{
  "firstName": "Эльдар",
  "lastName": "Муратулы",
  "age": 21,
  "illness": "Зрение"
}

GET http://localhost:8080/api/patients


