spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

server.forward-headers-strategy=framework

management.endpoint.health.show-details=never

logging.level.org.springframework.security=WARN
