spring.datasource.url=jdbc:postgresql://localhost:1234/hospital_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

app.jwt.secret=ZHVtbXktc3VwZXItc2VjdXJlLWp3dC1rZXktZm9yLWhvc3BpdGFsLW1hbmFnZW1lbnQtc3lzdGVtLTEyMw==
app.jwt.expiration=86400000
app.file.storage.path=uploads
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

logging.level.root=INFO
logging.level.com.turatbekuly.amir.hospitalmanagementsystem=INFO
logging.level.org.springframework.security=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n
